Upgrade torch in GitHub workflows to 1.7.1
The [recent workflow](https://github.com/rafidka/adawat/runs/1647076274)
failed on GitHub due to the following errors:

```
ERROR: Could not find a version that satisfies the requirement torch==1.5.1
ERROR: No matching distribution found for torch==1.5.1
```

Apparently, torch 1.51 is not available anymore on pip, so upgrading to
torch 1.7.1.